[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/terms-of-service"
  to = "/terms-of-service-1"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
